/*
 * sevensegment.c
 *
 *  Created on: Dec 14, 2019
 *      Author: sayed
 */

#include "sevensegment.h"

void sevensegment_Init() {
	SET_BIT(SEVEN_SEGMENT_ENABLE_PORT_DIR, SEVENSEGMENT1_ENABLE);
	SET_BIT(SEVEN_SEGMENT_ENABLE_PORT_DIR, SEVENSEGMENT1_ENABLE);
#ifdef HIGH_NIBBLE
	SEVEN_SEGMENT_PORT_DIR = 0xF0;
#else
	SEVEN_SEGMENT_PORT_DIR = 0x0F;

#endif
	SET_BIT(SEVEN_SEGMENT_ENABLE_PORT, SEVENSEGMENT1_ENABLE);
	SET_BIT(SEVEN_SEGMENT_ENABLE_PORT, SEVENSEGMENT2_ENABLE);
}
void sevensegment_BCDupdate(uint8 value) {
	uint8_t temp;
	temp = value % 10;
	SET_BIT(SEVEN_SEGMENT_ENABLE_PORT, SEVENSEGMENT1_ENABLE);
	CLR_BIT(SEVEN_SEGMENT_ENABLE_PORT, SEVENSEGMENT2_ENABLE);
	SEVEN_SEGMENT_PORT = temp;
	_delay_ms(1);
	temp = value / 10;
	CLR_BIT(SEVEN_SEGMENT_ENABLE_PORT, SEVENSEGMENT1_ENABLE);
	SET_BIT(SEVEN_SEGMENT_ENABLE_PORT, SEVENSEGMENT2_ENABLE);
	SEVEN_SEGMENT_PORT = temp;
	_delay_ms(1);

}
